### ISSUE TITLE
Mac Mini Fails to Unlock AI on macOS 15.1 beta

### ISSUE THREAD

**Issue by owenzhao** [Kyle-Ye/XcodeLLMEligible#11]
### Additional Information

Mac Mini China。 macOS 15.1 beta。

The AI features already worked with Xcode. But even after I changed the region, language, and Siri language to US/English/English, I still don’t have AI on macOS. As my developer account is Chinese, I can’t log in with an English Apple ID—the iCloud sync database would be too inconvenient to debug that way.

So I created a new account, also set the region, language and Siri preferences there, then logged in with my US Apple ID. Still not working.

The final straw was running the cracking program without disabling SIP in my new account, then rebooting and still not getting AI on macOS.

I’m at a loss for what to do next, so I’ll share my experience here and see if anyone has any insights into where I might have gone wrong.

**Comment by Kyle-Ye** [comment]
Have no time to study the waitlist logic yet.

This tool can only help to circumstance the local OS check.

Some direction I may do later:

- Capture the network packet or analyse the Setting.app to see what information the "join waitlist" is sending.
- If it sends your SKU/hardware information again, we need to patch the Settings app or modify the request to hack it. Otherwise it may due to some magic server logic on Apple side. And I have no idea what to fix this for you too.

**Comment by Gawain12** [comment]
Device: M2 Macbook Air 15.3 inch, 16G+256G
OS: 15.1 beta

Same here, I'm using the US region, language, and the US Apple ID, rebooting many times, still does not work.

<img width="464" alt="image" src="https://github.com/user-attachments/assets/99172d33-3c75-4239-b55e-c9c75a0269c9">

<img width="249" alt="image" src="https://github.com/user-attachments/assets/f9bb1c4f-d435-4eec-b9df-917524006427">

<img width="539" alt="image" src="https://github.com/user-attachments/assets/ec67b968-a5fd-411b-8596-ea1a23b60f76">
<img width="481" alt="image" src="https://github.com/user-attachments/assets/594a59ce-f34b-4359-827f-be74d2756cdf">

I’ve tried both script and manual installation. They all indicate that the installation was successful, but it actually wasn’t. I have no idea what to do if I missed anything. 
(No sure if it matters, I clicked About System Setting It shows Version 15.0 (15.0) instead of 15.1

**Comment by Kyle-Ye** [comment]
@Gawain12

The script is for Xcode LLM.

Could you confirm the result of running `./eligibility_util getDomainAnswer --domain-name OS_ELIGIBILITY_DOMAIN_GREYMATTER`.

If it is not `OS_ELIGIBILITY_ANSWER_ELIGIBLE`, please run `./eligibility_util forceDomainAnswer --domain-name OS_ELIGIBILITY_DOMAIN_GREYMATTER --answer 4`.

**Comment by Gawain12** [comment]
<img width="756" alt="image" src="https://github.com/user-attachments/assets/7b5e8a80-a99f-48ad-b77e-94a6b5bc71da">
The manual installation I mentioned before seems to be successful, but I still have no AI features.

**Comment by Kyle-Ye** [comment]
> So I created a new account, also set the region, language and Siri preferences there, then logged in with my US Apple ID. Still not working.

Hi @owenzhao , I'm trying to reproduce your issue here.

Which of the following steps best describes your situation?

1. Running `./eligibility_util_sip getDomainAnswer --domain-name OS_ELIGIBILITY_DOMAIN_GREYMATTER` and get `OS_ELIGIBILITY_ANSWER_ELIGIBLE`
2. See `Apple Intelligence & Siri` in your Setting App.
3. Joining waitlist and see "Joined Waitlist" result
<img width="827" alt="screenshot" src="https://github.com/user-attachments/assets/22441f53-d098-42b2-8fd8-81d76907f5d5">
4. Receiving the available notification.

**Comment by owenzhao** [comment]
Got an error.

SIP disabled.

```bash
aiuser@zhaoxins-Mac-mini-M1 Downloads % ./eligibility_util_sip getDomainAnswer --domain-name OS_ELIGIBILITY_DOMAIN_GREYMATTER
OS_ELIGIBILITY_ANSWER_NOT_ELIGIBLE
aiuser@zhaoxins-Mac-mini-M1 Downloads % ./eligibility_util_sip forceDomainAnswer --domain-name OS_ELIGIBILITY_DOMAIN_GREYMATTER --answer 4
Force domain answer failed: errorNum 54
aiuser@zhaoxins-Mac-mini-M1 Downloads % sudo ./eligibility_util_sip forceDomainAnswer --domain-name OS_ELIGIBILITY_DOMAIN_GREYMATTER --answer 4 
Password:
Sorry, try again.
Password:
Force domain answer failed: errorNum 54
aiuser@zhaoxins-Mac-mini-M1 Downloads % 
```

**Comment by owenzhao** [comment]
I don't know what the error number 54 means. 

I came across a tweet mentioning that the Apple AI function in macOS would be activated, but with a caveat: it requires macOS to be installed on the internal SSD. Currently, my macOS installation is on an external SSD.

After backing up my data, I intend to upgrade to an internal SSD to potentially access this new functionality.

**Comment by owenzhao** [comment]
Update me on your current situation.

I have installed macOS 15.1 beta on my internal SSD, but I am still getting the same error 54 issue. However, I noticed that while manual installation results in errors, script-based installation is successful. This suggests that there might be missing or incorrectly formatted steps in the manual installation process.

I encountered new issues during the application process for Apple's AI program. 

I was able to see the application for Apple's AI program on my Chinese Apple ID, but after clicking on it, I still found myself in an unsubmitted status. Then, upon creating a new account with no connection to any Apple IDs and applying, I managed to submit the application successfully. However, despite having submitted it half an hour ago, it hasn't been approved yet. Finally, running the automated installation script on my external SSD resulted in success, allowing me to proceed without issues. When trying to apply from an account with a US-based Apple ID, it showed that I had already applied. Therefore, I am uncertain whether the application process is tied to the Apple ID or the device itself.

**Comment by owenzhao** [comment]
Got it! 

<img width="827" alt="Screenshot 2024-08-02 at 10 46 48 AM" src="https://github.com/user-attachments/assets/b914a237-7600-4c24-be5e-3e26611e2e34">

**Comment by Kyle-Ye** [comment]
> Got an error.
> 
> SIP disabled.

errorNum 54 means you do not have the permission here.

See https://github.com/Kyle-Ye/eligibility/blob/8d524089df1341b186852a3eee4b951f0a7502da/eligibilityd/main.m#L206-L210

`eligibility_util_sip` removes such entitlement so that it can be run on SIP enabled device. And it can only perform "getDomainAnswer" related command.

Disable SIP and use `eligibility_util` to resolve the issue.

> This suggests that there might be missing or incorrectly formatted steps in the manual installation process.

No. They are the same. The script just performs method 1 or method 2 automatically according to your status. (SIP disable + boot-args -> Method 1. Otherwise method 2)
