### ISSUE TITLE
[Method 2] 

### ISSUE THREAD

**Issue by JsonKit** [Kyle-Ye/XcodeLLMEligible#31]
### JSON Output

![image](https://github.com/user-attachments/assets/f2e6fc12-9c27-41c0-ae70-e8642354b4a3)

### Upload Compressed Archive

![image](https://github.com/user-attachments/assets/0aa3a35c-7720-42c4-9fcd-a98325b1adb6)

### Additional Information

![image](https://github.com/user-attachments/assets/5e08b7a2-e648-4712-9251-1674f858fa93)

**Comment by Kyle-Ye** [comment]
Please provide your OS information. Thanks

**Comment by narakai** [comment]
same issue here, os version 15.0.1

**Comment by Kyle-Ye** [comment]
2 Issues here:

1. It is expected method 2 might fail after an OS update.

Since the override structure may change over time. You may need to use method 1 to unlock it (Method 1 will also produce the latest override file method 2 is using)

2. Can't run `eligibility_util_sip` issue.

I need more information to diagnostic the issue. eg. the MD5 value of your downloaded binary by `md5 /tmp/eligibility_util_sip`

**Comment by JsonKit** [comment]
> 1. Please provide your OS information.
> 2. Also for eligibility_util_sip issue, could you provide the MD5 value of the binary by `md5 /tmp/eligibility_util_sip`
> 
> Thanks

@Kyle-Ye , Thank you for your reply, I have already made it using method 1
