### ISSUE TITLE
[Method 1] Mac Bricked after OTA

### ISSUE THREAD

**Issue by EraserCN** [Kyle-Ye/XcodeLLMEligible#34]
### Additional Information

I've been using method 1 to enable Apple Intelligence on 15.1 Beta 3. But after auto updating to Beta 4, my Mac got bricked and had to DFU restore it. Tested on the same model without using neither method 1 or 2 before updating, and the Mac didn't get bricked. It's possible that method 1 could brick your Mac.

**Comment by Kyle-Ye** [comment]
> I've been using method 1 to enable Apple Intelligence on 15.1 Beta 3. But after auto updating to Beta 4, my Mac got bricked and had to DFU restore it.

There are many factors which would make it bricked. eg. Keep disabling SIP, custom boot-args or simply beta version of macOS is just unstable.

If you only disable SIP, set boot-args, run method 1 and then restore them back, there should not have only issue. Basically what it does is just create a plain override file. And in the worst case, it will only affect the daemon process of eligibilityd.

If you want me to follow up/investigate the issue, please provide more information here.

eg. The detail log of kernel panic.

Also since Apple has already introduced macOS 15.1 RC, I do not think we should waste time on investigating macOS 15.1 Beta 3 related issue here.
