### ISSUE TITLE
[Method 1] Seems to work for external drive installation as well

### ISSUE THREAD

**Issue by larryqiann** [Kyle-Ye/XcodeLLMEligible#41]
### Additional Information

Just followed the steps to do this after receiving a message that Apple Intelligence was not available when booting off of an external drive. It seems that the process has been successful, and after the requisite four reboots, the page in settings now says "Preparing". Thank you! I will report back if something isn't working.

macOS 15.1 release version, M1 Mac Mini booting off Thunderbolt 3 SSD + 16GB RAM.

**Comment by DrJapan** [comment]
Did it work?

**Comment by larryqiann** [comment]
Yes, Apple Intelligence is working fine now after leaving it overnight. I haven't tried the Xcode stuff yet since I don't have it installed though.

**Comment by Kyle-Ye** [comment]
Yes. 

Besides locale, language and device region check, the original Apple Intelligence (greymatter) also has a external boot check.

The repo can workaround it too.

**Comment by DrJapan** [comment]
Is there a way to get the computer to not jump to preparing right away?  I don't see it downloading any files.

**Comment by Kyle-Ye** [comment]
The repo's tool only guarantee Step 1 and Step 2 here.

https://github.com/Kyle-Ye/XcodeLLMEligible?tab=readme-ov-file#other-apple-intelligence-related-issue

For further steps, it is determined by other macOS's framework or Apple's remote Server and it is not covered by the repo. (Have not investigated such logic since it should just work as long as you have a good Internet connection)

If you can't join the waitlist, please login a supported country's Apple ID.

If you keeps preparing, my suggestion is try reboot and restart the whole process.
