### ISSUE TITLE
[其他]Will performing these methods on the China (Mainland) version of the MacBook affect the official AppleCare warranty policy? 请问国行MacBook执行了这些方法，是否会影响到Apple官方的Apple Care保修政策？

### ISSUE THREAD

**Issue by loongyat** [Kyle-Ye/XcodeLLMEligible#49]

**Comment by Kyle-Ye** [comment]
I'm not a *lawyer*. But the answer is probably no since every operation (disable SIP / modify the backup file) is recoverable by the uninstall process or a fresh reinstall of macOS.

Let me emphasize the following statement again.

**If you choose to use this project, you do so at your own risk and are responsible for compliance with any applicable laws.**

**The author of this project is not responsible for any consequences that may arise from your use of this project.**
